User.destroy_all
Deck.destroy_all
Card.destroy_all

user1 = User.create(username: "username1")

deck1 = Deck.create(deck_name: "deck1", user_id: 1) 

card1 = Card.create(card_name: "Nucleus", image_src: "https://www.genome.gov/sites/default/files/tg/en/illustration/nucleus.jpg", description: "The nucleus is one of the most obvious parts of the cell when you look at a picture of the cell. It's in the middle of the cell, and the nucleus contains all of the cell's chromosomes, which encode the genetic material. So this is really an important part of the cell to protect. The nucleus has a membrane around it that keeps all the chromosomes inside and makes the distinction between the chromosomes being inside the nucleus and the other organelles and components of the cell staying outside. Sometimes things like RNA need to traffic between the nucleus and the cytoplasm, and so there are pores in this nuclear membrane that allow molecules to go in and out of the nucleus. It used to be thought that the nuclear membrane only allowed molecules to go out, but now it's realized that there is an active process also for bringing molecules into the nucleus.", note: "note1")

card2 = Card.create(card_name: "Ribosome", image_src: "https://www.genome.gov/sites/default/files/tg/en/illustration/ribosome.jpg", description: "A ribosome is a cellular particle made of RNA and protein that serves as the site for protein synthesis in the cell. The ribosome reads the sequence of the messenger RNA (mRNA) and, using the genetic code, translates the sequence of RNA bases into a sequence of amino acids.", note: "note2")

card3 = Card.create(card_name: "Endoplasmic Reticulum (Rough)", image_src: "https://www.genome.gov/sites/default/files/tg/en/illustration/endoplasmic_reticulum_rough.jpg", description: "Endoplasmic reticulum is a network of membranes inside a cell through which proteins and other molecules move. Proteins are assembled at organelles called ribosomes. When proteins are destined to be part of the cell membrane or exported from the cell, the ribosomes assembling them attach to the endoplasmic reticulum, giving it a rough appearance.", note: "note3")

card4 = Card.create(card_name: "Endoplasmic Reticulum (Smooth)", image_src: "https://www.genome.gov/sites/default/files/tg/en/illustration/endoplasmic_reticulum_smooth.jpg", description: "Endoplasmic reticulum is a network of membranes inside a cell through which proteins and other molecules move. Proteins are assembled at organelles called ribosomes. When proteins are destined to be part of the cell membrane or exported from the cell, the ribosomes assembling them attach to the endoplasmic reticulum, giving it a rough appearance. Smooth endoplasmic reticulum lacks ribosomes and helps synthesize and concentrate various substances needed by the cell.", note: "note4")

card5 = Card.create(card_name: "Golgi Body", image_src: "https://www.genome.gov/sites/default/files/tg/en/illustration/golgi_body.jpg", description: "A Golgi body, also known as a Golgi apparatus, is a cell organelle that helps process and package proteins and lipid molecules, especially proteins destined to be exported from the cell. Named after its discoverer, Camillo Golgi, the Golgi body appears as a series of stacked membranes.", note: "note5")

card6 = Card.create(card_name: "Lysosome", image_src: "https://www.genome.gov/sites/default/files/tg/en/illustration/lysosome.jpg", description: "A lysosome is a membrane-bound cell organelle that contains digestive enzymes. Lysosomes are involved with various cell processes. They break down excess or worn-out cell parts. They may be used to destroy invading viruses and bacteria. If the cell is damaged beyond repair, lysosomes can help it to self-destruct in a process called programmed cell death, or apoptosis.", note: "note6")

card7 = Card.create(card_name: "​Mitochondria", image_src: "https://www.genome.gov/sites/default/files/tg/en/illustration/mitochondria.jpg", description: "Mitochondria are membrane-bound cell organelles (mitochondrion, singular) that generate most of the chemical energy needed to power the cell's biochemical reactions. Chemical energy produced by the mitochondria is stored in a small molecule called adenosine triphosphate (ATP). Mitochondria contain their own small chromosomes. Generally, mitochondria, and therefore mitochondrial DNA, are inherited only from the mother.", note: "note7")

deckcard1 = DeckCard.create(card_id: card1.id, deck_id: deck1.id)